### ISSUE TITLE
Some [ID] entries in the text version do not adhere to the documented format

### ISSUE THREAD

**Issue by oskar-taubert** [aqlaboratory/proteinnet#14]
e.g. 
`[ID]`
`3MKH_d3mkhd1`

should this be
`3MKH_3_D` or `3MKH_1_D`?
Is that chain_id correct?

looking at the pdb entry for 3MKH, `3MKH_4_D` seems most likely without looking further into it.

In text/casp11/training30 there are 3661 of these either malformed or undocumented IDs.

**Comment by thavlik** [comment]
https://github.com/aqlaboratory/proteinnet/issues/1#issuecomment-375270286

**Comment by oskar-taubert** [comment]
Thanks! Missed that somehow.
