### ISSUE TITLE
ProteinNet (predictive) and DiversityNet-Proteins (generative) benchmarks

### ISSUE THREAD

**Issue by mostafachatillon** [aqlaboratory/proteinnet#2]
Hello Mohammed,

This ProteinNet benchmark for predictive models is great, but are you interested in doing a similar benchmark for generative models of proteins?  

I introduced this benchmark, called 'DiversityNet-Proteins' here (it's a variant of the DiversityNet-Chemistry benchmark): 

https://medium.com/the-ai-lab/diversitynet-a-collaborative-benchmark-for-generative-ai-models-in-chemistry-f1b9cc669cba#c837

Tell me if you are interested!
Mostapha

**Comment by alquraishi** [comment]
Thanks for your interest! For the time being there’s still a lot to do in getting the raw data, etc, prepared for ProteinNet that I unfortunately don’t have the bandwidth for another project. Also, unlike the prediction case with CASP, it’s not clear to me what a meaningful benchmark for generative protein modeling would look like. There may be some cool things that one can do, but I think they will all be non-trivial.
