### ISSUE TITLE
Model and code of 'End-to-end differentiable learning of protein structure'

### ISSUE THREAD

**Issue by mostafachatillon** [aqlaboratory/proteinnet#3]
Hello Mohammed,

I am looking for the model and code of your paper 'End-to-end differentiable learning of protein structure'. Has it been released?

**Comment by rdk** [comment]
Same thing here. Do you plan to release the code?

**Comment by alquraishi** [comment]
Yes I do plan to release the code! It's just taking a while because of other projects, but stay tuned.

**Comment by kad-ecoli** [comment]
Hello Mohammed,
Looks like this issue has been closed 4 months ago, even though the model and code has not been released yet. Now that the manuscript is review completed, do you have an estimated time on when it can be released?

**Comment by alquraishi** [comment]
Hi, it's taken me a little longer than I expected due to other responsibilities. Expect the code / models to be released within a few weeks.

**Comment by alquraishi** [comment]
The code is now available [here](https://github.com/aqlaboratory/rgn).

**Comment by jostmey** [comment]
Wow thanks!
