### ISSUE TITLE
Units of measurement for 3D structure

### ISSUE THREAD

**Issue by isaachenrion** [aqlaboratory/proteinnet#4]
Hi.
I am trying to use these datasets for contact prediction. A contact is defined as a pair of residues within 8A of each other. However, when I compute the pairwise distances of residues for proteins in this dataset, they are typically in the thousands and none are 8A away from each other. What are the units used?
Thanks

**Comment by alquraishi** [comment]
Hi, sorry about the late response. I missed this somehow. The units used are picometers.
