### ISSUE TITLE
Obtaining MSA data

### ISSUE THREAD

**Issue by EricAlcaide** [aqlaboratory/proteinnet#6]
Hi, 
Is there anyway to get the MSA data from the text-based files?

Thanks in advance

**Comment by alquraishi** [comment]
Hi, the MSA data is too large to have available as a direct download. However I have a Globus endpoint set up for direct transfer. Feel free to contact me through [email](mailto:alquraishi@hms.harvard.edu) and I will send you the instructions. Right now it's just ProteinNet 12 that's available.
